fabtools/nodejs.py
Without `pty=False` the `run()` command returns back a json with a garbage like '\x1b[?25h\x1b[0G\x1b[K\x1b[?25h\x1b[0G\x1b[K' at the end, which causes `json.loads(res)` to fail.
=> Fix nodejs.package_version fails to read json

fabtools/require/users.py
Currently, if the user provides a username with leading whitespace, it totally borks the following commands.
If you prefer I raise an exception instead of stripping the string, I could do that.
=> Add username whitespace removal to require.users.sudoer

fabtools/require/postgres.py
create_role changed to createrole in the example
=> Fixed typo in require.postgres.user docs

fabtools/files.py, fabtools/require/nginx.py
`fabtools.services` -> `fabtools.service`, see http://fabtools.readthedocs.org/en/latest/api/service.html.
=> Fix a typo in a docstring

fabtools/postgres.py, fabtools/tests/test_postgres.py
Creating postgres users with dashes in username was not working for me. e.g.
require.postgres.user("foo-user", password=None)
If, in the generated SQL, username is in double quotes, it works.
=> In fabtools.postgres.create_user, put username in double quotes.

fabtools/python_setuptools.py
Use Python 3 compatible print statement when checking setuptools. Otherwise the function always returns False.
=> py3k compatible setuptools check

fabtools/__init__.py, fabtools/conda.py, fabtools/require/__init__.py, fabtools/require/conda.py, fabtools/tests/functional_tests/test_conda.py
The [conda](http://conda.pydata.org/docs/) package manager is gaining popularity, mostly in the scientific Python community. It allows installation of binary packages in separate environments, similar to Python virtualenvs, but not limited to Python packages.
The tools added in these commits (fabtools.conda, fabtools.require.conda) allow the installation of miniconda (a minimal conda environment) as well as setting up conda environments, package installation etc., much like the fabtools.python and fabtools.require.python packages
=> Add support for conda package manager

fabtools/disk.py
It seems, that the sfdisk have changed the output result with the newer version. In the older version, the partition type = "Id=xx" and in the newer version, the partion type = "type=xx". This fix work for older and newer version
=> Fix different sfdisk version

fabtools/vagrant.py
Split needs to happen only once in order to get two values. Vagrantfile can output strings containing many space characters which results in exception "ValueError: too many values to unpack"
=> Change maxsplit argument value to 1.

fabtools/require/system.py
/var/lib/locales/supported.d/local is no longer present on Ubuntu 16.04 and previous versions also work with /etc/locale.gen as config file, refs #325
=> Remove dependency on /var/lib/locales/supported.d/local for Ubuntu

fabtools/vagrant.py
The idea is to provide better support for multi-vagrant + fabric + fabtools usage patterns like `fab production packages` where the corresponding fabfile.py might look something like this:
``` python
@task
def production():
env.hosts = ['vagrant_box_1', 'vagrant_box_2', 'vagrant_box_3']
@task
def packages():
with vagrant_settings():
fabtools.require.python.packages(["nltk", "scikit-learn"])
```
I think this makes it slightly easier to manage multi-machine vagrant setups. 
If this is something that gets incorporated, I'd be happy to update #202 to also use the `_name_or_host_string` function in a similar way.
Please note that I wasn't exactly sure how this should affect the behavior of the `vagrant` task. Depending on what happens with #177, I could imagine incorporating a similar type of …
=> use env.host_string if no 'name' is specified with vagrant

fabtools/require/files.py
Hi!
Function `requires.files.file(url)` fails when the url contains the character `&`, as found e.g. in Amazon S3 download links, and many more places.
Taking a look to the source code, wget is invoked the following way:
```
func('wget --progress=dot:mega %(url)s -O %(path)s' % locals())
```
The problem could be easily solved using double quotes around `%(url)s` and `%(path)s` in the following way:
```
func('wget --progress=dot:mega "%(url)s" -O "%(path)s"' % locals())
```
Thanks!
Related issue: https://github.com/ronnix/fabtools/issues/261
=> Fix requires.files.file(url) when url contains '&'

fabtools/system.py
I've handled SUSE like operating systems in this patch.
Could use the file `/etc/SuSE-release`, however according to the file this is due to be deprecated, hence the decision to use `lsb_release`.
=> Handle SUSE in distrib_id

fabtools/deb.py, fabtools/tests/test_deb.py
The fabtools.deb.apt_key_exists function only checks for keys matching in `/etc/apt/trusted.gpg`, but when you run fabtools.deb.add_apt_key with this `postgres` key on Ubuntu 12.04 it is actually installed in `/etc/apt/trusted.gpg.d/apt.postgresql.org.gpg`. As a result, this code snippet ends up downloading and reinstalling the apt key every time this it is run.
``` python
if not fabtools.deb.apt_key_exists('7FCC7D46ACCC4CF8'):
fabtools.deb.add_apt_key(
url='https://www.postgresql.org/media/keys/ACCC4CF8.asc',
keyid='7FCC7D46ACCC4CF8',
)
fabtools.require.deb.source('postgresql',
'http://apt.postgresql.org/pub/repos/apt/',
'precise-pgdg',
'main')
```
Might be nice to generalize this a bit by having a `fabtools.require.deb.apt_key` function.
=> apt_key_exists doesn't work properly

fabtools/require/deb.py
I would like the function `fabtools.require.deb.package` [(doc)](https://fabtools.readthedocs.org/en/0.19.0/api/require/deb.html#fabtools.require.deb.package) have the parameter `option` which is available in function `fabtools.deb.install` [(doc)](https://fabtools.readthedocs.org/en/0.19.0/api/deb.html#fabtools.deb.install).
That parameter could be useful for passing the parameter `--no-install-recommends` for example.
Related issue: #287
=> Add param "options" to require.deb.package

fabtools/require/deb.py
add-apt-repository Ubuntu package:
- 'python-software-properties' in 12.04 (precise)
- 'software-properties-common' in 14.04 (trusty)
http://packages.ubuntu.com/precise/all/python-software-properties/filelist
http://packages.ubuntu.com/trusty/all/software-properties-common/filelist
=> add-apt-repository moved to package software-properties-common in 14.04

fabtools/system.py
Fix for bug when attempting to identify distribution vis lsb_release.
Typo and dead code fixed.   Added raspberry pi raspbian distort to
resolve to debian.
=> system - distribution identification fix

fabtools/systemd.py
Because status won't exit when there is more than a screen full of output to show and this causes fabtools to hang.
=> Use systemd is-active instead of status

setup.py
on fabric documentation
http://www.fabfile.org/installing-1.x.html#basic-installation
Fabric is best installed via pip; to ensure you get Fabric 1 instead of the new but incompatible Fabric 2, specify <2.0:
=> fix install fab 1.x 

fabtools/python.py
Pip should be run as a module instead of a script. It is also consistent with how `pip_cmd` is used on `install`. Currently `is_pip_installed` always returns false leading to reinstallation multiple times. It also makes it impossible to pin a specific version of pip.
=> Run pip command as a module instead of as a script

fabtools/mysql.py
While all other things being passed are being quoted, `password` gets passed unquoted leading to failure when there are special characters in the password.
=> Quote the password before passing to sshpass
